// temos dois tipos de problemas 
	//'Error' que e codigo escrito errado (sintaxi) e 
	// Exception que e os erro que acontece durante 
// As exeçoes das versoes 3.3+ e diferente 3.3- 
// Tenha cuidado pra não colocar exeção desnecessaria

import zipfile

try:
    banco_zip = zipfile.ZipFile("saida.zip")
    banco_zip.extractall(path="banco")
    banco_zip.close()
except FileNotFoundError:
    print("Arquivo inexistente")
except PermissionError as pme:
    print("Erro de permissao")


//////////////////////////////////////////////////////////////////////////
// Ele tratara todas as exeçoes filhas de OSError

import zipfile

try:
    banco_zip = zipfile.ZipFile( )
    banco_zip.extractall(path="banco")
    banco_zip.close()
except OSError as ose: # E possivel tratar as duas de uma vez, ja que as duas herdam de OSerror
    print("Algum problema ao ler o arquivo {}"
    .format(ose.filename))



//////////////////////////////////////////////////////////////////////////
// uso de dupla

import zipfile

try:
    banco_zip = zipfile.ZipFile("saida.zip")
    banco_zip.extractall(path="banco")
    banco_zip.close()
except (FileNotFoundError, PermissionError):
    print("Algum problema ao ler o arquivo")